#!/usr/bin/env sh
# Kedge one-command local run (issue #41).
#
#   ./deploy/local/up.sh              # first run: generates .env, builds, starts
#   KEDGE_PORT=9090 ./deploy/local/up.sh   # (first run only) pick another port
#
# Requirements: git, docker (with the compose plugin). Everything else is bundled.
set -eu

DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$DIR/.env"
COMPOSE="docker compose --env-file $ENV_FILE -f $DIR/compose.yml"

command -v docker >/dev/null 2>&1 || { echo "docker is required but not installed." >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "the docker compose plugin is required." >&2; exit 1; }

if [ ! -f "$ENV_FILE" ]; then
  echo "==> First run: generating $ENV_FILE (keys and secrets are random, kept out of git)"
  PORT="${KEDGE_PORT:-8080}"
  cat > "$ENV_FILE" <<EOF
# Generated by up.sh on first run — safe to edit, never committed.
KEDGE_PORT=${PORT}
# The public origin. For LAN access from other devices, change to
# http://<this-machine's-ip>:${PORT} and restart (cookies bind to this host).
APP_URL=http://localhost:${PORT}
APP_KEY=base64:$(openssl rand -base64 32)
DB_DATABASE=kedge
DB_USERNAME=kedge
DB_PASSWORD=$(openssl rand -hex 16)
PROJECTION_SHARED_SECRET=$(openssl rand -hex 32)
DIAGRAM_SHARED_SECRET=$(openssl rand -hex 32)
SESSION_SECURE_COOKIE=false
# GitHub sign-in stays hidden until you register an OAuth app and fill these in:
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
EOF
fi

PORT="$(grep '^KEDGE_PORT=' "$ENV_FILE" | cut -d= -f2)"
URL="$(grep '^APP_URL=' "$ENV_FILE" | cut -d= -f2-)"

echo "==> Building and starting Kedge (first build takes a few minutes)"
$COMPOSE up -d --build

echo "==> Waiting for Kedge to answer on ${URL}/up"
i=0
until curl -sf -o /dev/null --max-time 5 "http://localhost:${PORT}/up" 2>/dev/null; do
  i=$((i + 1))
  if [ "$i" -gt 60 ]; then
    echo "Timed out waiting for the app. Logs:" >&2
    $COMPOSE logs --tail 50 api proxy web >&2
    exit 1
  fi
  sleep 5
done

echo ""
echo "  Kedge is running → ${URL}"
echo ""
echo "  stop:      docker compose --env-file $ENV_FILE -f $DIR/compose.yml down"
echo "  reset all: docker compose --env-file $ENV_FILE -f $DIR/compose.yml down -v"
echo "  upgrade:   git pull && $0"
