#!/usr/bin/env bash
#
# Boot the Kedge API for the Playwright journey against a throwaway database.
#
# The E2E seam must be deterministic and must never touch a developer's real
# dev database. So the API runs under its own `e2e` environment: a generated
# api/.env.e2e (never committed) plus a fresh api/database/e2e.sqlite migrated
# from scratch on every boot. Both are picked up because APP_ENV=e2e is in the
# `php artisan serve` passthrough allowlist, so Laravel loads .env.e2e in the
# served worker too (a plain DB_DATABASE override would NOT survive the serve
# subprocess). The dev's api/.env and database.sqlite are left untouched.
#
# Invoked by playwright.config.ts's webServer; can also be run by hand.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$(cd "${SCRIPT_DIR}/../../api" && pwd)"
cd "${API_DIR}"

ENV_FILE="${API_DIR}/.env.e2e"
DB_FILE="${API_DIR}/database/e2e.sqlite"
PORT="${API_PORT:-8000}"

# APP_ENV=e2e makes every artisan call below (and the served worker) read
# .env.e2e instead of .env.
export APP_ENV=e2e

# Generate a fresh scratch env every run. Overrides go at the TOP: Laravel's
# dotenv is first-occurrence-wins, so these beat the identically-named lines in
# the example appended below (APP_ENV, DB_*, MAIL_MAILER). Everything else — the
# auth-handshake knobs (SESSION_DOMAIN / SANCTUM_STATEFUL_DOMAINS / CORS) and the
# empty APP_KEY that key:generate fills — comes straight from the committed
# example, so the E2E env can never silently drift from a real deployment.
{
  echo "# Generated by web/e2e/serve-api.sh — throwaway E2E env. Do not commit."
  echo "APP_ENV=e2e"
  echo "DB_CONNECTION=sqlite"
  echo "DB_DATABASE=${DB_FILE}"
  echo "MAIL_MAILER=log"
  echo ""
  cat "${API_DIR}/.env.example"
} >"${ENV_FILE}"

php artisan key:generate --force

# Fresh SQLite file, migrated from zero — no state survives between runs.
rm -f "${DB_FILE}"
touch "${DB_FILE}"
php artisan migrate --force

# --no-reload: no file watcher (deterministic) and a single served process.
exec php artisan serve --host=127.0.0.1 --port="${PORT}" --no-reload
